version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-network
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull tinyllama:1.1b && wait"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - ollama-network

volumes:
  ollama-data:
  open-webui-data:

networks:
  ollama-network:
    driver: bridge
